clear
clc

syms l2 alfa
%{
syms u v tetaZ w tetaY tetaX up vp tetaZp wp tetaYp tetaXp

Tc01 = [cos(tetaY), 0, sin(tetaY); 0, 1, 0; -sin(tetaY), 0, cos(tetaY)];
Tc10 = Tc01.';
Tc12 = [cos(tetaZ), -sin(tetaZ), 0; sin(tetaZ), cos(tetaZ), 0; 0, 0, 1];
Tc21 = Tc12.';
Tc23 = [1, 0, 0; 0, cos(tetaX), -sin(tetaX); 0, sin(tetaX), cos(tetaX)];
Tc32 = Tc23.';

%Velocidade linear vC:
IIvS = [up; vp; wp];

%Velocidade angular wC escrita na base B2:
B2IwC = Tc21*Tc10*[0; tetaYp; 0] + Tc21*[0; 0; tetaZp] + [tetaXp; 0; 0];
B2IwCdisp = [ tetaXp + tetaYp*sin(tetaZ); tetaYp*cos(tetaZ); tetaZp];
B2IwCsimpl = [ tetaXp + tetaYp*tetaZ; tetaYp; tetaZp];

%Velocidade linear de dm:
B2IvS = Tc21*Tc10*IIvS;
B2IwCtil = [0, -B2IwC(3), B2IwC(2); 
    B2IwC(3), 0, -B2IwC(1); 
    -B2IwC(2), B2IwC(1), 0];
SSrS2 = [0; l2*cos(alfa); l2*sin(alfa)];
B2SrS2 = Tc23*SSrS2;
%{
erro = simplify(cross(B2IwC,B2SrS2) - B2IwCtil*B2SrS2);
ad = 1;
%ok!
%}
B2Iv2 = B2IvS + B2IwCtil*B2SrS2;
v22 = simplify(B2Iv2.'*B2Iv2); 
v22disp =...
    (l2*cos(tetaX + alfa)*(tetaXp + tetaYp*sin(tetaZ)) +...
     wp*cos(tetaY) + up*sin(tetaY))^2 +...
    (vp*sin(tetaZ) -...
     tetaZp*l2*cos(tetaX + alfa) +...
     up*cos(tetaY)*cos(tetaZ) -...
     wp*cos(tetaZ)*sin(tetaY) +...
     tetaYp*cos(tetaZ)*l2*sin(tetaX + alfa))^2 +...
    (l2*sin(tetaX + alfa)*(tetaXp + tetaYp*sin(tetaZ)) -...
     vp*cos(tetaZ) +...
     up*cos(tetaY)*sin(tetaZ) -...
     wp*sin(tetaY)*sin(tetaZ))^2;
%{
erro = simplify(v22 - v22disp);
ad = 1;
%ok!
%} 
v22simpl =...
    (up + vp*tetaZ - wp*tetaY + l2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)))^2 +...
    (vp - up*tetaZ - l2*sin(tetaX + alfa)*(tetaXp + tetaYp*tetaZ))^2 +...
    (wp + up*tetaY + l2*cos(tetaX + alfa)*(tetaXp + tetaYp*tetaZ))^2;

%%
syms rho A Jp J
Jbb = diag([Jp, J, J]);
PsiT_x = rho*(A*(IIvS.'*IIvS) + B2IwCsimpl.'*Jbb*B2IwCsimpl);

PsiT_ln = rho*(A*(up^2 + vp^2 + wp^2) + Jp*tetaXp^2 + J*tetaYp^2 + J*tetaZp^2);
PsiT_nln = rho*Jp*(2*tetaXp*tetaZ*tetaYp + tetaZ^2*tetaYp^2);
%{
erro = simplify(PsiT_x - (PsiT_ln + PsiT_nln));
ad = 1;
%ok!
%}
%}

%%
%Consideração das aproximações via elementos finitos
syms t x xj le rho A Jp J
syms u1 v1 tetaZ1 w1 tetaY1 tetaX1 u2 v2 tetaZ2 w2 tetaY2 tetaX2
syms up1 vp1 tetaZp1 wp1 tetaYp1 tetaXp1 up2 vp2 tetaZp2 wp2 tetaYp2 tetaXp2
syms upp1 vpp1 tetaZpp1 wpp1 tetaYpp1 tetaXpp1 upp2 vpp2 tetaZpp2 wpp2 tetaYpp2 tetaXpp2

uj = [u1; v1; tetaZ1; w1; tetaY1; tetaX1;...
    u2; v2; tetaZ2; w2; tetaY2; tetaX2];
upj = [up1; vp1; tetaZp1; wp1; tetaYp1; tetaXp1;...
    up2; vp2; tetaZp2; wp2; tetaYp2; tetaXp2];
%
uppj = [upp1; vpp1; tetaZpp1; wpp1; tetaYpp1; tetaXpp1;...
    upp2; vpp2; tetaZpp2; wpp2; tetaYpp2; tetaXpp2];
%}

xi = (x - xj)/le;

n1 = 1 - xi;
n2 = xi;
H1 = 1 - 3*xi^2 + 2*xi^3;
H2 = le*(xi - 2*xi^2 + xi^3);
H3 = 3*xi^2 - 2*xi^3;
H4 = le*(-xi^2 + xi^3);

dn1dx = diff(n1,x);
dn2dx = diff(n2,x);
dH1dx = diff(H1,x);
dH2dx = diff(H2,x);
dH3dx = diff(H3,x);
dH4dx = diff(H4,x);

d2H1dx2 = diff(dH1dx,x);
d2H2dx2 = diff(dH2dx,x);
d2H3dx2 = diff(dH3dx,x);
d2H4dx2 = diff(dH4dx,x);

clear xi
syms xi

dn1dx = simplify(subs(dn1dx,x,le*xi + xj));
dn2dx = simplify(subs(dn2dx,x,le*xi + xj));
dH1dx = simplify(subs(dH1dx,x,le*xi + xj));
dH2dx = simplify(subs(dH2dx,x,le*xi + xj));
dH3dx = simplify(subs(dH3dx,x,le*xi + xj));
dH4dx = simplify(subs(dH4dx,x,le*xi + xj));

d2H1dx2 = simplify(subs(d2H1dx2,x,le*xi + xj));
d2H2dx2 = simplify(subs(d2H2dx2,x,le*xi + xj));
d2H3dx2 = simplify(subs(d2H3dx2,x,le*xi + xj));
d2H4dx2 = simplify(subs(d2H4dx2,x,le*xi + xj));

Nu = [n1, 0, 0, 0, 0, 0, n2, 0, 0, 0, 0, 0];
Nv = ([0, H1, H2, 0, 0, 0,...
    0, H3, H4, 0, 0, 0]);
NtetaZ = ([0, dH1dx, dH2dx, 0, 0, 0,...
    0, dH3dx, dH4dx, 0, 0, 0]);
Nw = ([0, 0, 0, H1, -H2, 0,...
    0, 0, 0, H3, -H4, 0]);
NtetaY = ([0, 0, 0, -dH1dx, dH2dx, 0,...
    0, 0, 0, -dH3dx, dH4dx, 0]);
NtetaX = ([0, 0, 0, 0, 0, n1, 0, 0, 0, 0, 0, n2]);

dNu_dx = [dn1dx, 0, 0, 0, 0, 0, dn2dx, 0, 0, 0, 0, 0];
dNv_dx = ([0, dH1dx, dH2dx, 0, 0, 0,...
    0, dH3dx, dH4dx, 0, 0, 0]);
dNtetaZ_dx = ([0, d2H1dx2, d2H2dx2, 0, 0, 0,...
    0, d2H3dx2, d2H4dx2, 0, 0, 0]);
dNw_dx = ([0, 0, 0, dH1dx, -dH2dx, 0,...
    0, 0, 0, dH3dx, -dH4dx, 0]);
dNtetaY_dx = ([0, 0, 0, -d2H1dx2, d2H2dx2, 0,...
    0, 0, 0, -d2H3dx2, d2H4dx2, 0]);
dNtetaX_dx = ([0, 0, 0, 0, 0, dn1dx, 0, 0, 0, 0, 0, dn2dx]);

%u = Nu*uj;
%v = Nv*uj;
tetaZ = NtetaZ*uj;
%w = Nw*uj;
tetaY = NtetaY*uj;
tetaX = NtetaX*uj;

up = Nu*upj;
vp = Nv*upj;
tetaZp = NtetaZ*upj;
wp = Nw*upj;
tetaYp = NtetaY*upj;
tetaXp = NtetaX*upj;

%
upp = Nu*uppj;
vpp = Nv*uppj;
tetaZpp = NtetaZ*uppj;
wpp = Nw*uppj;
tetaYpp = NtetaY*uppj;
tetaXpp = NtetaX*uppj;
%}

Tc01 = [cos(tetaY), 0, sin(tetaY); 0, 1, 0; -sin(tetaY), 0, cos(tetaY)];
Tc10 = Tc01.';
Tc12 = [cos(tetaZ), -sin(tetaZ), 0; sin(tetaZ), cos(tetaZ), 0; 0, 0, 1];
Tc21 = Tc12.';
Tc23 = [1, 0, 0; 0, cos(tetaX), -sin(tetaX); 0, sin(tetaX), cos(tetaX)];
Tc32 = Tc23.';

%Velocidade linear vS do CG do corpo:
IIvS = [up; vp; wp];

%Velocidade angular wC escrita na base B2:
B2IwC = Tc21*Tc10*[0; tetaYp; 0] + Tc21*[0; 0; tetaZp] + [tetaXp; 0; 0];
B2IwCdisp = [ tetaXp + tetaYp*sin(tetaZ); tetaYp*cos(tetaZ); tetaZp];
B2IwCsimpl = [ tetaXp + tetaYp*tetaZ; tetaYp; tetaZp];

%Velocidade linear de dm:
B2IvS = Tc21*Tc10*IIvS;
B2IwCtil = [0, -B2IwC(3), B2IwC(2); 
    B2IwC(3), 0, -B2IwC(1); 
    -B2IwC(2), B2IwC(1), 0];
SSrS2 = [0; l2*cos(alfa); l2*sin(alfa)];
B2SrS2 = Tc23*SSrS2;
%{
erro = simplify(cross(B2IwC,B2SrS2) - B2IwCtil*B2SrS2);
ad = 1;
%ok!
%}
B2Iv2 = B2IvS + B2IwCtil*B2SrS2;
v22 = simplify(B2Iv2.'*B2Iv2); 
v22disp =...
    (l2*cos(tetaX + alfa)*(tetaXp + tetaYp*sin(tetaZ)) +...
     wp*cos(tetaY) + up*sin(tetaY))^2 +...
    (vp*sin(tetaZ) -...
     tetaZp*l2*cos(tetaX + alfa) +...
     up*cos(tetaY)*cos(tetaZ) -...
     wp*cos(tetaZ)*sin(tetaY) +...
     tetaYp*cos(tetaZ)*l2*sin(tetaX + alfa))^2 +...
    (l2*sin(tetaX + alfa)*(tetaXp + tetaYp*sin(tetaZ)) -...
     vp*cos(tetaZ) +...
     up*cos(tetaY)*sin(tetaZ) -...
     wp*sin(tetaY)*sin(tetaZ))^2;
%{
erro = simplify(v22 - v22disp);
ad = 1;
%ok!
%} 
%
v22simplv2 =...
    (up^2 + vp^2*tetaZ^2 + wp^2*tetaY^2 + l2^2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))^2 +...
     2*up*vp*tetaZ - 2*up*wp*tetaY + 2*up*l2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) -...
     2*vp*wp*tetaZ*tetaY + 2*vp*tetaZ*l2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) -...
     2*wp*tetaY*l2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))) +...
    (vp^2 + up^2*tetaZ^2 + l2^2*(sin(tetaX + alfa))^2*(tetaXp + tetaYp*tetaZ)^2 -...
     2*vp*up*tetaZ - 2*vp*l2*sin(tetaX + alfa)*(tetaXp + tetaYp*tetaZ) +...
     2*up*tetaZ*l2*sin(tetaX + alfa)*(tetaXp + tetaYp*tetaZ)) +...
    (wp^2 + up^2*tetaY^2 + l2^2*(cos(tetaX + alfa))^2*(tetaXp + tetaYp*tetaZ)^2 +...
     2*wp*up*tetaY + 2*wp*l2*cos(tetaX + alfa)*(tetaXp + tetaYp*tetaZ) +...
     2*up*tetaY*l2*cos(tetaX + alfa)*(tetaXp + tetaYp*tetaZ));
%{
v22simpl =...
    (up + vp*tetaZ - wp*tetaY + l2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)))^2 +...
    (vp - up*tetaZ - l2*sin(tetaX + alfa)*(tetaXp + tetaYp*tetaZ))^2 +...
    (wp + up*tetaY + l2*cos(tetaX + alfa)*(tetaXp + tetaYp*tetaZ))^2;
erro = simplify(v22simpl - v22simplv2);
ad = 1;
%ok!
%}
%{
v22simplv3 = up^2 + vp^2 + wp^2 + l2^2*(tetaXp + tetaYp*tetaZ)^2 +...
     tetaZ^2*(vp^2 + up^2) + tetaY^2*(wp^2 + up^2) +...
     2*l2*(tetaXp + tetaYp*tetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
     2*l2*(up - wp*tetaY)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
     l2^2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))^2 -...
     2*vp*(wp*tetaZ*tetaY + tetaZ*l2*tetaZp*cos(tetaX + alfa) + l2*tetaXp*sin(tetaX + alfa));
erro = simplify(v22simplv2 - v22simplv3);
ad = 1;
%ok!
%}

%%
syms rho A Jp J
%{
Jbb = diag([Jp, J, J]);
PsiT_x = rho*(A*(IIvS.'*IIvS) + B2IwCsimpl.'*Jbb*B2IwCsimpl);

PsiT_ln = rho*(A*(up^2 + vp^2 + wp^2) + Jp*tetaXp^2 + J*tetaYp^2 + J*tetaZp^2);
PsiT_nln = rho*Jp*(2*tetaXp*tetaZ*tetaYp + tetaZ^2*tetaYp^2);
%{
erro = simplify(PsiT_x - (PsiT_ln + PsiT_nln));
ad = 1;
%ok!
%}

dPsiT_lndupj = rho*(A*(2*up*Nu.' + 2*vp*Nv.' + 2*wp*Nw.') +...
    Jp*2*tetaXp*NtetaX.' + J*2*tetaYp*NtetaY.' + J*2*tetaZp*NtetaZ.');
%{
dPsiT_lndupjRef = gradient(PsiT_ln,upj);
erro = simplify(dPsiT_lndupjRef - dPsiT_lndupj);
ad = 1;
%ok!
%}
dPsiT_nlndupj = rho*Jp*...
    (2*tetaZ*(NtetaX.'*tetaYp + tetaXp*NtetaY.') +...
     tetaZ^2*2*tetaYp*NtetaY.');
%{
dPsiT_nlndupjRef = gradient(PsiT_nln,upj);
erro = simplify(dPsiT_nlndupjRef - dPsiT_nlndupj);
ad = 1;
%ok!
%}
dPsiT_nlnduj = rho*Jp*NtetaZ.'*(2*tetaXp*tetaYp + 2*tetaZ*tetaYp^2);
%{
dPsiT_nlndujRef = gradient(PsiT_nln,uj);
erro = simplify(dPsiT_nlndujRef - dPsiT_nlnduj);
ad = 1;
%ok!
%}
%}

%%
%{
syms dm
%Movimento de dm:
PsiTdm_ln = dm*(up^2 + vp^2 + wp^2 + l2^2*tetaXp^2);
PsiTdm_nln = dm*(l2^2*(2*tetaXp*tetaYp*tetaZ + tetaYp^2*tetaZ^2) +...
    tetaZ^2*(vp^2 + up^2) + tetaY^2*(wp^2 + up^2) +...
    2*l2*(tetaXp + tetaYp*tetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
    2*l2*(up - wp*tetaY)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
    l2^2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))^2 -...
    2*vp*(wp*tetaZ*tetaY + tetaZ*l2*tetaZp*cos(tetaX + alfa) + l2*tetaXp*sin(tetaX + alfa)));
%{
v22simplv3 = up^2 + vp^2 + wp^2 + l2^2*tetaXp^2 +...
    l2^2*(2*tetaXp*tetaYp*tetaZ + tetaYp^2*tetaZ^2) +...
    tetaZ^2*(vp^2 + up^2) + tetaY^2*(wp^2 + up^2) +...
    2*l2*(tetaXp + tetaYp*tetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
    2*l2*(up - wp*tetaY)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
    l2^2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))^2 -...
    2*vp*(wp*tetaZ*tetaY + tetaZ*l2*tetaZp*cos(tetaX + alfa) + l2*tetaXp*sin(tetaX + alfa));
PsiTdm = dm*v22simplv3;
erro = simplify(PsiTdm - (PsiTdm_ln + PsiTdm_nln));
ad = 1;
%ok!
%}
dPsiTdm_lndupj = dm*(2*up*Nu.' + 2*vp*Nv.' + 2*wp*Nw.' + l2^2*2*tetaXp*NtetaX.');
%{
dPsiTdm_lndupjRef = gradient(PsiTdm_ln,upj);
erro = simplify(dPsiTdm_lndupjRef - dPsiTdm_lndupj);
ad = 1;
%ok!
%}
dPsiTdm_nlndupj = dm*...
    (l2^2*(2*tetaZ*(NtetaX.'*tetaYp + tetaXp*NtetaY.') + 2*tetaYp*NtetaY.'*tetaZ^2) +...
     tetaZ^2*(2*vp*Nv.' + 2*up*Nu.') + tetaY^2*(2*wp*Nw.' + 2*up*Nu.') +...
     2*l2*((NtetaX.' + NtetaY.'*tetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
           (tetaXp + tetaYp*tetaZ)*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))) +...
     2*l2*((Nu.' - Nw.'*tetaY)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
           (up - wp*tetaY)*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))) +...
     l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) -...
     2*(Nv.'*(wp*tetaZ*tetaY + tetaZ*l2*tetaZp*cos(tetaX + alfa) + l2*tetaXp*sin(tetaX + alfa)) +...
        vp*(Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa))));
%{
dPsiTdm_nlndupjRef = gradient(PsiTdm_nln,upj);
erro = simplify(dPsiTdm_nlndupjRef - dPsiTdm_nlndupj);
ad = 1;
%ok!
%}
dPsiTdm_nlnduj = dm*(l2^2*(2*tetaXp*tetaYp + tetaYp^2*2*tetaZ)*NtetaZ.' +...
    2*tetaZ*NtetaZ.'*(vp^2 + up^2) +...
    2*tetaY*NtetaY.'*(wp^2 + up^2) +...
    2*l2*((tetaYp*NtetaZ.')*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
          (tetaXp + tetaYp*tetaZ)*(up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                       (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) - wp*sin(tetaX + alfa)*NtetaX.')) +...
    2*l2*((-wp*NtetaY.')*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
          (up - wp*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.') +...
    l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.' -...
    2*vp*(wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
    l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
    l2*tetaXp*cos(tetaX + alfa)*NtetaX.'));
%{
dPsiTdm_nlndujRef = gradient(PsiTdm_nln,uj);
erro = simplify(dPsiTdm_nlndujRef - dPsiTdm_nlnduj);
ad = 1;
%ok!
%}
%}

%%
%Derivadas em relação a uj e upj:
%Expressões relativas ao eixo principal:
%{
M2uppj = 2*rho*Jp*(tetaZ*(NtetaX.'*tetaYpp + NtetaY.'*tetaXpp) + tetaZ^2*(NtetaY.'*tetaYpp));
%}
dM2uppjdujT = 2*rho*Jp*((NtetaX.'*tetaYpp + NtetaY.'*tetaXpp)*NtetaZ + (NtetaY.'*tetaYpp)*2*tetaZ*NtetaZ);
%{
dM2uppjdujTRef = jacobian(M2uppj,uj);
erro = simplify(dM2uppjdujTRef - dM2uppjdujT);
ad = 1;
%ok!
%}
dM2uppjduppjT = 2*rho*Jp*(tetaZ*(NtetaX.'*NtetaY + NtetaY.'*NtetaX) + tetaZ^2*(NtetaY.'*NtetaY));
M2j = dM2uppjduppjT;
%{
dM2uppjduppjTRef = jacobian(M2uppj,uppj);
erro = simplify(dM2uppjduppjTRef - dM2uppjduppjT);
ad = 1;
%ok!
%}

%{
gCj = 2*rho*Jp*...
    (NtetaX.'*tetaZp*tetaYp +...
     NtetaY.'*tetaZp*(tetaXp + 2*tetaZ*tetaYp) -...
     NtetaZ.'*tetaYp*(tetaXp + tetaZ*tetaYp));
%}
dgCjdujT =  2*rho*Jp*...
    (NtetaY.'*tetaZp*(2*NtetaZ*tetaYp) -...
     NtetaZ.'*tetaYp*(NtetaZ*tetaYp));
%{
dgCjdujTRef = jacobian(gCj,uj);
erro = simplify(dgCjdujTRef - dgCjdujT);
ad = 1;
%ok!
%}
dgCjdupjT = 2*rho*Jp*...
    (NtetaX.'*(NtetaZ*tetaYp + tetaZp*NtetaY) +...
     NtetaY.'*(NtetaZ*(tetaXp + 2*tetaZ*tetaYp) + tetaZp*(NtetaX + 2*tetaZ*NtetaY)) -...
     NtetaZ.'*(NtetaY*(tetaXp + tetaZ*tetaYp) + tetaYp*(NtetaX + tetaZ*NtetaY)));
%{
dgCjdupjTRef = jacobian(gCj,upj);
erro = simplify(dgCjdupjTRef - dgCjdupjT);
ad = 1;
%}

%%
%Expressões relativas a dm:
syms dm
%{
syms dm
M2uppjdm = ...
    dm*...
    (l2^2*(2*tetaZ*(NtetaX.'*tetaYpp + tetaXpp*NtetaY.') +...
           2*tetaYpp*tetaZ^2*NtetaY.') +...
     (tetaZ^2*(2*vpp*Nv.' + 2*upp*Nu.')) +...
     (tetaY^2*(2*wpp*Nw.' + 2*upp*Nu.'))) +...
    dm*...
    (2*l2*(((NtetaX.' + NtetaY.'*tetaZ)*((upp*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
                                         (wpp*cos(tetaX + alfa)))) +...
           ((tetaXpp + (tetaYpp*tetaZ))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))))) +...
    dm*...
    (2*l2*(((Nu.' - Nw.'*tetaY)*((tetaYpp*sin(tetaX + alfa)) -...
                                 (tetaZpp*cos(tetaX + alfa)))) +...
           ((upp - (wpp*tetaY))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))))) +...
    dm*...
    (l2^2*2*(((tetaYpp*sin(tetaX + alfa)) - (tetaZpp*cos(tetaX + alfa)))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))) -...
     2*(Nv.'*((wpp*tetaZ*tetaY) +...
              (tetaZ*tetaZpp*cos(tetaX + alfa))*l2 +...
              (tetaXpp*sin(tetaX + alfa))*l2) +...
        (vpp*(Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa)))));
%}
dM2uppjdmdujT = ...
    dm*...
    (l2^2*(2*(NtetaX.'*tetaYpp + tetaXpp*NtetaY.')*NtetaZ +...
           2*tetaYpp*NtetaY.'*2*tetaZ*NtetaZ) +...
     ((2*vpp*Nv.' + 2*upp*Nu.')*2*tetaZ*NtetaZ) +...
     ((2*wpp*Nw.' + 2*upp*Nu.')*2*tetaY*NtetaY)) +...
    dm*...
    (2*l2*((((NtetaY.'*NtetaZ)*((upp*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
                                         (wpp*cos(tetaX + alfa))) +...
             (NtetaX.' + NtetaY.'*tetaZ)*((upp*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) + (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX))) +...
                                         (-wpp*sin(tetaX + alfa)*NtetaX)))) +...
           ((Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))*(tetaYpp*NtetaZ) +...
            (tetaXpp + (tetaYpp*tetaZ))*(-Nw.'*sin(tetaX + alfa)*NtetaX + Nu.'*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) + (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX)))))) +...
    dm*...
    (2*l2*(((-Nw.'*NtetaY)*((tetaYpp*sin(tetaX + alfa)) -...
                                 (tetaZpp*cos(tetaX + alfa))) +...
            (Nu.' - Nw.'*tetaY)*(tetaYpp*cos(tetaX + alfa)*NtetaX +...
                                 tetaZpp*sin(tetaX + alfa)*NtetaX)) +...
           ((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(-wpp*NtetaY) + (upp - (wpp*tetaY))*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX)))) +...
    dm*...
    (l2^2*2*((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(tetaYpp*cos(tetaX + alfa)*NtetaX + tetaZpp*sin(tetaX + alfa)*NtetaX) +...
             (tetaYpp*sin(tetaX + alfa) - tetaZpp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX)) -...
     2*(Nv.'*(wpp*(NtetaZ*tetaY + tetaZ*NtetaY) +...
              tetaZpp*(NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)*l2 +...
              tetaXpp*cos(tetaX + alfa)*NtetaX*l2) +...
        (vpp*(Nw.'*(NtetaZ*tetaY + tetaZ*NtetaY) +...
              NtetaZ.'*(NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)*l2 +...
              NtetaX.'*cos(tetaX + alfa)*NtetaX*l2))));
%{
dM2uppjdmdujTRef = jacobian(M2uppjdm,uj);
erro = simplify(dM2uppjdmdujTRef - dM2uppjdmdujT);
ad = 1;
%ok!
%}
dM2uppjdmduppjT = ...
    dm*...
    (l2^2*(2*tetaZ*(NtetaX.'*NtetaY + NtetaY.'*NtetaX) +...
           2*tetaZ^2*(NtetaY.'*NtetaY)) +...
     (tetaZ^2*(2*(Nv.'*Nv) + 2*(Nu.'*Nu))) +...
     (tetaY^2*(2*(Nw.'*Nw) + 2*(Nu.'*Nu)))) +...
    dm*...
    (2*l2*(((NtetaX.' + NtetaY.'*tetaZ)*(((tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))*Nu) +...
                                         (cos(tetaX + alfa)*Nw))) +...
           ((Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))*(NtetaX + (NtetaY*tetaZ))))) +...
    dm*...
    (2*l2*(((Nu.' - Nw.'*tetaY)*((NtetaY*sin(tetaX + alfa)) -...
                                 (NtetaZ*cos(tetaX + alfa)))) +...
           ((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(Nu - (Nw*tetaY))))) +...
    dm*...
    (l2^2*2*((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))) -...
     2*(Nv.'*((Nw*tetaZ*tetaY) +...
              (tetaZ*NtetaZ*cos(tetaX + alfa))*l2 +...
              (NtetaX*sin(tetaX + alfa))*l2) +...
        ((Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa))*Nv)));
%{
dM2uppjdmduppjTRef = jacobian(M2uppjdm,uppj);
erro = simplify(dM2uppjdmduppjTRef - dM2uppjdmduppjT);
ad = 1;
%ok!
%}
M2jdm = dM2uppjdmduppjT;

ddMuppjdmduppj =...
    dm*...
    (2*l2*((NtetaX.')*(Nw*cos(tetaX + alfa)) +...
           (Nw.'*cos(tetaX + alfa))*(NtetaX))) +...
    dm*...
    (2*l2*(((Nu.')*(NtetaY*sin(tetaX + alfa) -...
                    NtetaZ*cos(tetaX + alfa))) +...
           ((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(Nu)))) +...
    dm*...
    (l2^2*2*((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))) -...
     2*(Nv.'*(NtetaX*sin(tetaX + alfa))*l2 +...
        (l2*NtetaX.'*sin(tetaX + alfa))*Nv));
dMjdm = ddMuppjdmduppj;
%{
teste1 = simplify(subs(M2jdm,...
    [u1, v1, tetaZ1, w1, tetaY1, tetaX1, u2, v2, tetaZ2, w2, tetaY2, tetaX2],...
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]));
ad1 = 1;
teste2 = simplify(subs(M2jdm - dMjdm,...
    [u1, v1, tetaZ1, w1, tetaY1, tetaX1, u2, v2, tetaZ2, w2, tetaY2, tetaX2],...
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]));
ad2 = 1;
%ok!
%}

%{
gCjdm = dm*...
    (l2^2*(2*(tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.')) +...
           2*(2*tetaZ*tetaYp*tetaZp)*NtetaY.') +...
     (2*tetaZ*tetaZp*(2*vp*Nv.' + 2*up*Nu.')) +...
     (2*tetaY*tetaYp*(2*wp*Nw.' + 2*up*Nu.'))) +...
    dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                         (-wp*sin(tetaX + alfa)*tetaXp))) +...
           (((tetaYp*tetaZp))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
            (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*tetaXp +...
                                     Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                           (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))))) +...
    dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (Nu.' - Nw.'*tetaY)*((tetaYp*cos(tetaX + alfa)*tetaXp) -...
                                 (-tetaZp*sin(tetaX + alfa)*tetaXp))) +...
           ((-(wp*tetaYp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
            (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)))) +...
    dm*...
    (l2^2*2*(((tetaYp*cos(tetaX + alfa)*tetaXp) - (-tetaZp*sin(tetaX + alfa)*tetaXp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
             (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)) -...
     2*(Nv.'*((wp*tetaZp*tetaY + wp*tetaZ*tetaYp) +...
              (tetaZp^2*cos(tetaX + alfa) - tetaZ*tetaZp*sin(tetaX + alfa)*tetaXp)*l2 +...
              (tetaXp^2*cos(tetaX + alfa))*l2) +...
        (vp*(Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
             l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
             l2*NtetaX.'*cos(tetaX + alfa)*tetaXp)))) -...
    dm*(l2^2*(2*tetaXp*tetaYp + tetaYp^2*2*tetaZ)*NtetaZ.' +...
    2*tetaZ*NtetaZ.'*(vp^2 + up^2) +...
    2*tetaY*NtetaY.'*(wp^2 + up^2) +...
    2*l2*((tetaYp*NtetaZ.')*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
          (tetaXp + tetaYp*tetaZ)*(up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                       (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) - wp*sin(tetaX + alfa)*NtetaX.')) +...
    2*l2*((-wp*NtetaY.')*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
          (up - wp*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.') +...
    l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.' -...
    2*vp*(wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
    l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
    l2*tetaXp*cos(tetaX + alfa)*NtetaX.'));
%}
%{
dgCjdmdujT01 = dm*...
    (l2^2*(2*(2*tetaYp*tetaZp)*(NtetaY.'*NtetaZ)) +...
     (2*tetaZp*(2*vp*Nv.' + 2*up*Nu.')*NtetaZ) +...
     (2*tetaYp*(2*wp*Nw.' + 2*up*Nu.')*NtetaY));
%{
dgCjdmdujT01Ref = jacobian(dm*...
    (l2^2*(2*(tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.')) +...
           2*(2*tetaZ*tetaYp*tetaZp)*NtetaY.') +...
     (2*tetaZ*tetaZp*(2*vp*Nv.' + 2*up*Nu.')) +...
     (2*tetaY*tetaYp*(2*wp*Nw.' + 2*up*Nu.'))),uj);
erro = simplify(dgCjdmdujT01Ref - dgCjdmdujT01);
ad = 1;
%ok!
%}
dgCjdmdujT02 = dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                   (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX)) -...
                               wp*sin(tetaX + alfa)*NtetaX) +...
            ((NtetaY.'*NtetaZ)*((up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                (-wp*sin(tetaX + alfa)*tetaXp)) +...
             (NtetaX.' + NtetaY.'*tetaZ)*((up*((tetaZp*cos(tetaX + alfa)*NtetaX + (NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)*tetaXp) +...
                                               (-tetaYp*sin(tetaX + alfa)*NtetaX - (NtetaY*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)*NtetaX)*tetaXp))) +...
                                          (-wp*cos(tetaX + alfa)*NtetaX*tetaXp)))) +...
           ((tetaYp*tetaZp)*(-Nw.'*sin(tetaX + alfa)*NtetaX +...
                             Nu.'*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                   (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX))) +...
            ((-Nw.'*sin(tetaX + alfa)*tetaXp +...
              Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                    (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))*(tetaYp*NtetaZ) +...
             (tetaXp + tetaYp*tetaZ)*(-Nw.'*cos(tetaX + alfa)*NtetaX*tetaXp +...
                                      Nu.'*((tetaZp*cos(tetaX + alfa)*NtetaX + (NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)*tetaXp) +...
                                            (-tetaYp*sin(tetaX + alfa)*NtetaX - (NtetaY*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)*NtetaX)*tetaXp)))))));
%{
dgCjdmdujT02Ref = jacobian(dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                         (-wp*sin(tetaX + alfa)*tetaXp))) +...
           (((tetaYp*tetaZp))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
            (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*tetaXp +...
                                     Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                           (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))))),uj);
erro = simplify(dgCjdmdujT02Ref - dgCjdmdujT02);
ad = 1;
%ok!
%}
dgCjdmdujT03 = dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX) +...
            ((-Nw.'*NtetaY)*((tetaYp*cos(tetaX + alfa)*tetaXp) +...
                             (tetaZp*sin(tetaX + alfa)*tetaXp)) +...
             (Nu.' - Nw.'*tetaY)*((-tetaYp*sin(tetaX + alfa)*NtetaX*tetaXp) -...
                                  (-tetaZp*cos(tetaX + alfa)*NtetaX*tetaXp)))) +...
           ((-wp*tetaYp)*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX) +...
            ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(-wp*NtetaY) +...
             (up - wp*tetaY)*(-NtetaY.'*sin(tetaX + alfa)*NtetaX*tetaXp + NtetaZ.'*cos(tetaX + alfa)*NtetaX*tetaXp)))));
%{
dgCjdmdujT03Ref = jacobian(dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (Nu.' - Nw.'*tetaY)*((tetaYp*cos(tetaX + alfa)*tetaXp) -...
                                 (-tetaZp*sin(tetaX + alfa)*tetaXp))) +...
           ((-(wp*tetaYp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
            (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)))),uj);
erro = simplify(dgCjdmdujT03Ref - dgCjdmdujT03);
ad = 1;
%ok!
%}
dgCjdmdujT04 = dm*...
    (l2^2*2*(((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(-tetaYp*sin(tetaX + alfa)*NtetaX*tetaXp + tetaZp*cos(tetaX + alfa)*NtetaX*tetaXp) +...
              (tetaYp*cos(tetaX + alfa)*tetaXp + tetaZp*sin(tetaX + alfa)*tetaXp)*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX)) +...
             ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX) +...
              (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(-NtetaY.'*sin(tetaX + alfa)*NtetaX*tetaXp + NtetaZ.'*cos(tetaX + alfa)*NtetaX*tetaXp))) -...
     2*(Nv.'*((wp*tetaZp*NtetaY + wp*NtetaZ*tetaYp) +...
              (-tetaZp^2*sin(tetaX + alfa)*NtetaX - (NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX)*tetaZp*tetaXp)*l2 +...
              (-tetaXp^2*sin(tetaX + alfa)*NtetaX)*l2) +...
        vp*(Nw.'*(tetaZp*NtetaY + NtetaZ*tetaYp) +...
            l2*NtetaZ.'*(-tetaZp*sin(tetaX + alfa)*NtetaX - (NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX)*tetaXp) -...
            l2*NtetaX.'*sin(tetaX + alfa)*NtetaX*tetaXp)));
%{
dgCjdmdujT04Ref = jacobian(dm*...
    (l2^2*2*(((tetaYp*cos(tetaX + alfa)*tetaXp) - (-tetaZp*sin(tetaX + alfa)*tetaXp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
             (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)) -...
     2*(Nv.'*((wp*tetaZp*tetaY + wp*tetaZ*tetaYp) +...
              (tetaZp^2*cos(tetaX + alfa) - tetaZ*tetaZp*sin(tetaX + alfa)*tetaXp)*l2 +...
              (tetaXp^2*cos(tetaX + alfa))*l2) +...
        (vp*(Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
             l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
             l2*NtetaX.'*cos(tetaX + alfa)*tetaXp)))),uj);
erro = simplify(dgCjdmdujT04Ref - dgCjdmdujT04);
ad = 1;
%ok!
%}
dgCjdmdujT05 = -dm*...
    (l2^2*NtetaZ.'*(tetaYp^2*2*NtetaZ) +...
     2*NtetaZ.'*(vp^2 + up^2)*NtetaZ +...
     2*NtetaY.'*(wp^2 + up^2)*NtetaY +...
     2*l2*((tetaYp*NtetaZ.')*(up*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                  (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX)) -...
                              wp*sin(tetaX + alfa)*NtetaX) +...
           ((up*((NtetaZ.'*cos(tetaX + alfa)*NtetaX +...
                  NtetaX.'*(NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)) +...
                 (-NtetaY.'*sin(tetaX + alfa)*NtetaX -...
                  NtetaX.'*(NtetaY*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)*NtetaX))) -...
             wp*NtetaX.'*cos(tetaX + alfa)*NtetaX)*(tetaXp + tetaYp*tetaZ) +...
            (up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                 (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) -...
             wp*sin(tetaX + alfa)*NtetaX.')*(tetaYp*NtetaZ))) +...
     2*l2*((-wp*NtetaY.')*(tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX) +...
           NtetaX.'*((-wp*NtetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                     (up - wp*tetaY)*(-tetaYp*sin(tetaX + alfa)*NtetaX + tetaZp*cos(tetaX + alfa)*NtetaX))) +...
     l2^2*2*NtetaX.'*((tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                      (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(-tetaYp*sin(tetaX + alfa)*NtetaX + tetaZp*cos(tetaX + alfa)*NtetaX)) -...
     2*vp*(wp*(NtetaZ.'*NtetaY + NtetaY.'*NtetaZ) +...
           l2*tetaZp*(-NtetaZ.'*sin(tetaX + alfa)*NtetaX - NtetaX.'*(NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX)) -...
           l2*tetaXp*NtetaX.'*sin(tetaX + alfa)*NtetaX));
%{
dgCjdmdujT05Ref = jacobian(-...
    dm*(l2^2*(2*tetaXp*tetaYp + tetaYp^2*2*tetaZ)*NtetaZ.' +...
    2*tetaZ*NtetaZ.'*(vp^2 + up^2) +...
    2*tetaY*NtetaY.'*(wp^2 + up^2) +...
    2*l2*((tetaYp*NtetaZ.')*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
          (tetaXp + tetaYp*tetaZ)*(up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                       (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) - wp*sin(tetaX + alfa)*NtetaX.')) +...
    2*l2*((-wp*NtetaY.')*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
          (up - wp*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.') +...
    l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.' -...
    2*vp*(wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
    l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
    l2*tetaXp*cos(tetaX + alfa)*NtetaX.')),uj);
erro = simplify(dgCjdmdujT05Ref - dgCjdmdujT05);
ad = 1;
%ok!
%}
%}
dgCjdmdujT = dm*...
    (l2^2*(2*(2*tetaYp*tetaZp)*(NtetaY.'*NtetaZ)) +...
     (2*tetaZp*(2*vp*Nv.' + 2*up*Nu.')*NtetaZ) +...
     (2*tetaYp*(2*wp*Nw.' + 2*up*Nu.')*NtetaY)) +...
    dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                   (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX)) -...
                               wp*sin(tetaX + alfa)*NtetaX) +...
            ((NtetaY.'*NtetaZ)*((up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                (-wp*sin(tetaX + alfa)*tetaXp)) +...
             (NtetaX.' + NtetaY.'*tetaZ)*((up*((tetaZp*cos(tetaX + alfa)*NtetaX + (NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)*tetaXp) +...
                                               (-tetaYp*sin(tetaX + alfa)*NtetaX - (NtetaY*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)*NtetaX)*tetaXp))) +...
                                          (-wp*cos(tetaX + alfa)*NtetaX*tetaXp)))) +...
           ((tetaYp*tetaZp)*(-Nw.'*sin(tetaX + alfa)*NtetaX +...
                             Nu.'*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                   (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX))) +...
            ((-Nw.'*sin(tetaX + alfa)*tetaXp +...
              Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                    (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))*(tetaYp*NtetaZ) +...
             (tetaXp + tetaYp*tetaZ)*(-Nw.'*cos(tetaX + alfa)*NtetaX*tetaXp +...
                                      Nu.'*((tetaZp*cos(tetaX + alfa)*NtetaX + (NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)*tetaXp) +...
                                            (-tetaYp*sin(tetaX + alfa)*NtetaX - (NtetaY*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)*NtetaX)*tetaXp))))))) +...
    dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX) +...
            ((-Nw.'*NtetaY)*((tetaYp*cos(tetaX + alfa)*tetaXp) +...
                             (tetaZp*sin(tetaX + alfa)*tetaXp)) +...
             (Nu.' - Nw.'*tetaY)*((-tetaYp*sin(tetaX + alfa)*NtetaX*tetaXp) -...
                                  (-tetaZp*cos(tetaX + alfa)*NtetaX*tetaXp)))) +...
           ((-wp*tetaYp)*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX) +...
            ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(-wp*NtetaY) +...
             (up - wp*tetaY)*(-NtetaY.'*sin(tetaX + alfa)*NtetaX*tetaXp + NtetaZ.'*cos(tetaX + alfa)*NtetaX*tetaXp))))) +...
    dm*...
    (l2^2*2*(((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(-tetaYp*sin(tetaX + alfa)*NtetaX*tetaXp + tetaZp*cos(tetaX + alfa)*NtetaX*tetaXp) +...
              (tetaYp*cos(tetaX + alfa)*tetaXp + tetaZp*sin(tetaX + alfa)*tetaXp)*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX)) +...
             ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX) +...
              (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(-NtetaY.'*sin(tetaX + alfa)*NtetaX*tetaXp + NtetaZ.'*cos(tetaX + alfa)*NtetaX*tetaXp))) -...
     2*(Nv.'*((wp*tetaZp*NtetaY + wp*NtetaZ*tetaYp) +...
              (-tetaZp^2*sin(tetaX + alfa)*NtetaX - (NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX)*tetaZp*tetaXp)*l2 +...
              (-tetaXp^2*sin(tetaX + alfa)*NtetaX)*l2) +...
        vp*(Nw.'*(tetaZp*NtetaY + NtetaZ*tetaYp) +...
            l2*NtetaZ.'*(-tetaZp*sin(tetaX + alfa)*NtetaX - (NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX)*tetaXp) -...
            l2*NtetaX.'*sin(tetaX + alfa)*NtetaX*tetaXp))) -...
    dm*...
    (l2^2*NtetaZ.'*(tetaYp^2*2*NtetaZ) +...
     2*NtetaZ.'*(vp^2 + up^2)*NtetaZ +...
     2*NtetaY.'*(wp^2 + up^2)*NtetaY +...
     2*l2*((tetaYp*NtetaZ.')*(up*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                  (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX)) -...
                              wp*sin(tetaX + alfa)*NtetaX) +...
           ((up*((NtetaZ.'*cos(tetaX + alfa)*NtetaX +...
                  NtetaX.'*(NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX)) +...
                 (-NtetaY.'*sin(tetaX + alfa)*NtetaX -...
                  NtetaX.'*(NtetaY*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)*NtetaX))) -...
             wp*NtetaX.'*cos(tetaX + alfa)*NtetaX)*(tetaXp + tetaYp*tetaZ) +...
            (up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                 (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) -...
             wp*sin(tetaX + alfa)*NtetaX.')*(tetaYp*NtetaZ))) +...
     2*l2*((-wp*NtetaY.')*(tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX) +...
           NtetaX.'*((-wp*NtetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                     (up - wp*tetaY)*(-tetaYp*sin(tetaX + alfa)*NtetaX + tetaZp*cos(tetaX + alfa)*NtetaX))) +...
     l2^2*2*NtetaX.'*((tetaYp*cos(tetaX + alfa)*NtetaX + tetaZp*sin(tetaX + alfa)*NtetaX)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                      (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(-tetaYp*sin(tetaX + alfa)*NtetaX + tetaZp*cos(tetaX + alfa)*NtetaX)) -...
     2*vp*(wp*(NtetaZ.'*NtetaY + NtetaY.'*NtetaZ) +...
           l2*tetaZp*(-NtetaZ.'*sin(tetaX + alfa)*NtetaX - NtetaX.'*(NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX)) -...
           l2*tetaXp*NtetaX.'*sin(tetaX + alfa)*NtetaX));
%{
dgCjdmdujTRef = jacobian(gCjdm,uj);
erro = simplify(dgCjdmdujTRef - dgCjdmdujT);
ad = 1;
%ok!
%}
%%
%{
dgCjdmdupjT01 = dm*...
    (l2^2*(2*(((NtetaX.'*tetaYp + tetaXp*NtetaY.')*NtetaZ +...
               tetaZp*(NtetaX.'*NtetaY + NtetaY.'*NtetaX))) +...
           2*(2*tetaZ)*NtetaY.'*(NtetaY*tetaZp + tetaYp*NtetaZ)) +...
     (2*tetaZ*((2*vp*Nv.' + 2*up*Nu.')*NtetaZ + 2*tetaZp*(Nv.'*Nv + Nu.'*Nu))) +...
     (2*tetaY*((2*wp*Nw.' + 2*up*Nu.')*NtetaY + 2*tetaYp*(Nw.'*Nw + Nu.'*Nu))));
%{
dgCjdmdupjT01Ref = jacobian(dm*...
    (l2^2*(2*(tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.')) +...
           2*(2*tetaZ*tetaYp*tetaZp)*NtetaY.') +...
     (2*tetaZ*tetaZp*(2*vp*Nv.' + 2*up*Nu.')) +...
     (2*tetaY*tetaYp*(2*wp*Nw.' + 2*up*Nu.'))),upj);
erro = simplify(dgCjdmdupjT01Ref - dgCjdmdupjT01);
ad = 1;
%ok!
%}
dgCjdmdupjT02 = dm*...
    (2*l2*((((NtetaY.'*NtetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
             (NtetaY.'*tetaZp)*(Nu*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + Nw*cos(tetaX + alfa))) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((Nu*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)) +...
                                          up*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                              (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX))) +...
                                         (-sin(tetaX + alfa)*(Nw*tetaXp + wp*NtetaX)))) +...
           ((Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))*(NtetaY*tetaZp + tetaYp*NtetaZ) +...
            ((-Nw.'*sin(tetaX + alfa)*tetaXp +...
              Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                    (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))*(NtetaX + NtetaY*tetaZ) +...
             (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*NtetaX +...
                                      Nu.'*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                            (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX)))))));
%{
dgCjdmdupjT02Ref = jacobian(dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                         (-wp*sin(tetaX + alfa)*tetaXp))) +...
           (((tetaYp*tetaZp))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
            (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*tetaXp +...
                                     Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                           (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))))),upj);
erro = simplify(dgCjdmdupjT02Ref - dgCjdmdupjT02);
ad = 1;
%ok!
%}
dgCjdmdupjT03 = dm*...
    (2*l2*((-Nw.'*(NtetaY*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
                   tetaYp*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))) +...
            (Nu.' - Nw.'*tetaY)*(cos(tetaX + alfa)*(NtetaY*tetaXp + tetaYp*NtetaX) +...
                                 sin(tetaX + alfa)*(NtetaZ*tetaXp + tetaZp*NtetaX))) +...
           (-(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(Nw*tetaYp + wp*NtetaY) +...
            ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(Nu - Nw*tetaY) +...
             (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX)))));
%{
dgCjdmdupjT03Ref = jacobian(dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (Nu.' - Nw.'*tetaY)*((tetaYp*cos(tetaX + alfa)*tetaXp) -...
                                 (-tetaZp*sin(tetaX + alfa)*tetaXp))) +...
           ((-(wp*tetaYp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
            (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)))),upj);
erro = simplify(dgCjdmdupjT03Ref - dgCjdmdupjT03);
ad = 1;
%ok!
%}
dgCjdmdupjT04 = dm*...
    (l2^2*2*((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(cos(tetaX + alfa)*(NtetaY*tetaXp + tetaYp*NtetaX) + sin(tetaX + alfa)*(NtetaZ*tetaXp + tetaZp*NtetaX)) +...
             ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa)) +...
              (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX))) -...
     2*(Nv.'*(((Nw*tetaZp + wp*NtetaZ)*tetaY + (Nw*tetaYp + wp*NtetaY)*tetaZ) +...
              (2*tetaZp*NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*(NtetaZ*tetaXp + tetaZp*NtetaX))*l2 +...
              (2*tetaXp*NtetaX*cos(tetaX + alfa))*l2) +...
        ((Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
          l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
          l2*NtetaX.'*cos(tetaX + alfa)*tetaXp)*Nv +...
         vp*(Nw.'*(NtetaZ*tetaY + tetaZ*NtetaY) +...
             l2*NtetaZ.'*(NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX) +...
             l2*NtetaX.'*cos(tetaX + alfa)*NtetaX))));
%{
dgCjdmdupjT04Ref = jacobian(dm*...
    (l2^2*2*(((tetaYp*cos(tetaX + alfa)*tetaXp) - (-tetaZp*sin(tetaX + alfa)*tetaXp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
             (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)) -...
     2*(Nv.'*((wp*tetaZp*tetaY + wp*tetaZ*tetaYp) +...
              (tetaZp^2*cos(tetaX + alfa) - tetaZ*tetaZp*sin(tetaX + alfa)*tetaXp)*l2 +...
              (tetaXp^2*cos(tetaX + alfa))*l2) +...
        (vp*(Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
             l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
             l2*NtetaX.'*cos(tetaX + alfa)*tetaXp)))),upj);
erro = simplify(dgCjdmdupjT04Ref - dgCjdmdupjT04);
ad = 1;
%ok!
%}
dgCjdmdupjT05 = dm*...
    (2*l2^2*NtetaZ.'*((NtetaX*tetaYp + tetaXp*NtetaY) + 2*tetaYp*NtetaY*tetaZ) +...
     2*tetaZ*NtetaZ.'*(2*vp*Nv + 2*up*Nu) +...
     2*tetaY*NtetaY.'*(2*wp*Nw + 2*up*Nu) +...
     2*l2*(((NtetaZ.'*NtetaY)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (tetaYp*NtetaZ.')*(Nu*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + Nw*cos(tetaX + alfa))) +...
           ((up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                 (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) -...
             wp*sin(tetaX + alfa)*NtetaX.')*(NtetaX + NtetaY*tetaZ) +...
            (tetaXp + tetaYp*tetaZ)*(((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                         (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.'))*Nu -...
                                     sin(tetaX + alfa)*(NtetaX.'*Nw)))) +...
     2*l2*(((-NtetaY.'*Nw)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (-wp*NtetaY.')*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))) +...
           NtetaX.'*((Nu - Nw*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                     (up - wp*tetaY)*(NtetaY*cos(tetaX + alfa) + NtetaZ*sin(tetaX + alfa)))) +...
     l2^2*2*NtetaX.'*((NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                      (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY*cos(tetaX + alfa) + NtetaZ*sin(tetaX + alfa))) -...
     2*((wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
         l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
         l2*tetaXp*cos(tetaX + alfa)*NtetaX.')*Nv +...
        vp*((NtetaZ.'*tetaY + tetaZ*NtetaY.')*Nw +...
            l2*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.')*NtetaZ +...
            l2*cos(tetaX + alfa)*(NtetaX.'*NtetaX))));
%{
dgCjdmdupjT05Ref = jacobian(dm*(l2^2*(2*tetaXp*tetaYp + tetaYp^2*2*tetaZ)*NtetaZ.' +...
    2*tetaZ*NtetaZ.'*(vp^2 + up^2) +...
    2*tetaY*NtetaY.'*(wp^2 + up^2) +...
    2*l2*((tetaYp*NtetaZ.')*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
          (tetaXp + tetaYp*tetaZ)*(up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                       (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) - wp*sin(tetaX + alfa)*NtetaX.')) +...
    2*l2*((-wp*NtetaY.')*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
          (up - wp*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.') +...
    l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.' -...
    2*vp*(wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
    l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
    l2*tetaXp*cos(tetaX + alfa)*NtetaX.')),upj);
erro = simplify(dgCjdmdupjT05Ref - dgCjdmdupjT05);
ad = 1;
%ok!
%}
%}
dgCjdmdupjT =...
    dm*...
    (l2^2*(2*(((NtetaX.'*tetaYp + tetaXp*NtetaY.')*NtetaZ +...
               tetaZp*(NtetaX.'*NtetaY + NtetaY.'*NtetaX))) +...
           2*(2*tetaZ)*NtetaY.'*(NtetaY*tetaZp + tetaYp*NtetaZ)) +...
     (2*tetaZ*((2*vp*Nv.' + 2*up*Nu.')*NtetaZ + 2*tetaZp*(Nv.'*Nv + Nu.'*Nu))) +...
     (2*tetaY*((2*wp*Nw.' + 2*up*Nu.')*NtetaY + 2*tetaYp*(Nw.'*Nw + Nu.'*Nu)))) +...
    dm*...
    (2*l2*((((NtetaY.'*NtetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
             (NtetaY.'*tetaZp)*(Nu*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + Nw*cos(tetaX + alfa))) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((Nu*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)) +...
                                          up*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                              (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX))) +...
                                         (-sin(tetaX + alfa)*(Nw*tetaXp + wp*NtetaX)))) +...
           ((Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))*(NtetaY*tetaZp + tetaYp*NtetaZ) +...
            ((-Nw.'*sin(tetaX + alfa)*tetaXp +...
              Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                    (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))*(NtetaX + NtetaY*tetaZ) +...
             (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*NtetaX +...
                                      Nu.'*((NtetaZ*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX) +...
                                            (NtetaY*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX))))))) +...
    dm*...
    (2*l2*((-Nw.'*(NtetaY*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
                   tetaYp*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))) +...
            (Nu.' - Nw.'*tetaY)*(cos(tetaX + alfa)*(NtetaY*tetaXp + tetaYp*NtetaX) +...
                                 sin(tetaX + alfa)*(NtetaZ*tetaXp + tetaZp*NtetaX))) +...
           (-(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(Nw*tetaYp + wp*NtetaY) +...
            ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(Nu - Nw*tetaY) +...
             (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX))))) +...
    dm*...
    (l2^2*2*((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(cos(tetaX + alfa)*(NtetaY*tetaXp + tetaYp*NtetaX) + sin(tetaX + alfa)*(NtetaZ*tetaXp + tetaZp*NtetaX)) +...
             ((NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa)) +...
              (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*NtetaX + NtetaZ.'*sin(tetaX + alfa)*NtetaX))) -...
     2*(Nv.'*(((Nw*tetaZp + wp*NtetaZ)*tetaY + (Nw*tetaYp + wp*NtetaY)*tetaZ) +...
              (2*tetaZp*NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*(NtetaZ*tetaXp + tetaZp*NtetaX))*l2 +...
              (2*tetaXp*NtetaX*cos(tetaX + alfa))*l2) +...
        ((Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
          l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
          l2*NtetaX.'*cos(tetaX + alfa)*tetaXp)*Nv +...
         vp*(Nw.'*(NtetaZ*tetaY + tetaZ*NtetaY) +...
             l2*NtetaZ.'*(NtetaZ*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX) +...
             l2*NtetaX.'*cos(tetaX + alfa)*NtetaX)))) -...
    dm*...
    (2*l2^2*NtetaZ.'*((NtetaX*tetaYp + tetaXp*NtetaY) + 2*tetaYp*NtetaY*tetaZ) +...
     2*tetaZ*NtetaZ.'*(2*vp*Nv + 2*up*Nu) +...
     2*tetaY*NtetaY.'*(2*wp*Nw + 2*up*Nu) +...
     2*l2*(((NtetaZ.'*NtetaY)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (tetaYp*NtetaZ.')*(Nu*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + Nw*cos(tetaX + alfa))) +...
           ((up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                 (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) -...
             wp*sin(tetaX + alfa)*NtetaX.')*(NtetaX + NtetaY*tetaZ) +...
            (tetaXp + tetaYp*tetaZ)*(((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                         (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.'))*Nu -...
                                     sin(tetaX + alfa)*(NtetaX.'*Nw)))) +...
     2*l2*(((-NtetaY.'*Nw)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (-wp*NtetaY.')*(NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))) +...
           NtetaX.'*((Nu - Nw*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                     (up - wp*tetaY)*(NtetaY*cos(tetaX + alfa) + NtetaZ*sin(tetaX + alfa)))) +...
     l2^2*2*NtetaX.'*((NtetaY*sin(tetaX + alfa) - NtetaZ*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa)) +...
                      (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY*cos(tetaX + alfa) + NtetaZ*sin(tetaX + alfa))) -...
     2*((wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
         l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
         l2*tetaXp*cos(tetaX + alfa)*NtetaX.')*Nv +...
        vp*((NtetaZ.'*tetaY + tetaZ*NtetaY.')*Nw +...
            l2*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.')*NtetaZ +...
            l2*cos(tetaX + alfa)*(NtetaX.'*NtetaX))));
%{
dgCjdmdupjTRef = jacobian(gCjdm,upj);
erro = simplify(dgCjdmdupjTRef - dgCjdmdupjT);
ad = 1;
%ok?
%}

%%
syms u1(t) v1(t) tetaZ1(t) w1(t) tetaY1(t) tetaX1(t) u2(t) v2(t) tetaZ2(t) w2(t) tetaY2(t) tetaX2(t)
uj = [u1; v1; tetaZ1; w1; tetaY1; tetaX1;...
    u2; v2; tetaZ2; w2; tetaY2; tetaX2];
upj = diff(uj,t);
uppj = diff(upj,t);

u = Nu*uj;
v = Nv*uj;
tetaZ = NtetaZ*uj;
w = Nw*uj;
tetaY = NtetaY*uj;
tetaX = NtetaX*uj;

up = Nu*upj;
vp = Nv*upj;
tetaZp = NtetaZ*upj;
wp = Nw*upj;
tetaYp = NtetaY*upj;
tetaXp = NtetaX*upj;

upp = Nu*uppj;
vpp = Nv*uppj;
tetaZpp = NtetaZ*uppj;
wpp = Nw*uppj;
tetaYpp = NtetaY*uppj;
tetaXpp = NtetaX*uppj;

dPsiT_lndupj = rho*(A*(2*up*Nu.' + 2*vp*Nv.' + 2*wp*Nw.') +...
    Jp*2*tetaXp*NtetaX.' + J*2*tetaYp*NtetaY.' + J*2*tetaZp*NtetaZ.');
dPsiT_nlndupj = rho*Jp*...
    (2*tetaZ*(NtetaX.'*tetaYp + tetaXp*NtetaY.') +...
     tetaZ^2*2*tetaYp*NtetaY.');
dPsiT_nlnduj = rho*Jp*NtetaZ.'*(2*tetaXp*tetaYp + 2*tetaZ*tetaYp^2);

d2PsiT_lndtdupj = 2*rho*(A*((Nu.'*Nu) + (Nv.'*Nv) + (Nw.'*Nw)) +...
    Jp*(NtetaX.'*NtetaX) + J*(NtetaY.'*NtetaY) + J*(NtetaZ.'*NtetaZ))*uppj;
%{
d2PsiT_lndtdupjRef = diff(dPsiT_lndupj,t);
erro = simplify(d2PsiT_lndtdupjRef - d2PsiT_lndtdupj);
ad = 1;
%ok!
%}
d2PsiT_nlndtdupj = 2*rho*Jp*...
    ((tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.') + tetaZ*(NtetaX.'*tetaYpp + tetaXpp*NtetaY.')) +...
     (2*tetaZ*tetaZp*tetaYp + tetaZ^2*tetaYpp)*NtetaY.');
%{
d2PsiT_nlndtdupjRef = diff(dPsiT_nlndupj,t);
erro = simplify(d2PsiT_nlndtdupjRef - d2PsiT_nlndtdupj);
ad = 1;
%ok!
%}

M1j = 2*rho*...
    (A*((Nu.'*Nu) + (Nv.'*Nv) + (Nw.'*Nw)) +...
     Jp*(NtetaX.'*NtetaX) +...
     J*(NtetaY.'*NtetaY) +...
     J*(NtetaZ.'*NtetaZ));
%{
erro = simplify(d2PsiT_lndtdupj - M1j*uppj);
ad = 1;
%ok!
%}

M2uppj = 2*rho*Jp*(tetaZ*(NtetaX.'*NtetaY + NtetaY.'*NtetaX) + tetaZ^2*(NtetaY.'*NtetaY))*uppj;
%{
gC1 = 2*rho*Jp*(tetaZp*tetaYp*NtetaX.' + tetaZp*(tetaXp + 2*tetaZ*tetaYp)*NtetaY.');
erro = simplify(d2PsiT_nlndtdupj - (M2uppj + gC1));
ad = 1;
%ok!
%}

gCj = 2*rho*Jp*...
    (NtetaX.'*tetaZp*tetaYp +...
     NtetaY.'*tetaZp*(tetaXp + 2*tetaZ*tetaYp) -...
     NtetaZ.'*tetaYp*(tetaXp + tetaZ*tetaYp));
%{
gC2 = -dPsiT_nlnduj;
gCjref = gC1 + gC2;
erro = simplify(gCjref - gCj);
ad = 1;
%ok!
%}


%%
%ELEMENTOS CONCENTRADOS
syms M1 M2b M3 Ip1 I1 Ip2b I2b Ip3 I3 Ip3m I3m dm

%%
%Movimento de dm:
dPsiTdm_lndupj = dm*(2*up*Nu.' + 2*vp*Nv.' + 2*wp*Nw.' + l2^2*2*tetaXp*NtetaX.');
dPsiTdm_nlndupj = dm*...
    (l2^2*(2*tetaZ*(NtetaX.'*tetaYp + tetaXp*NtetaY.') + 2*tetaYp*NtetaY.'*tetaZ^2) +...
     tetaZ^2*(2*vp*Nv.' + 2*up*Nu.') + tetaY^2*(2*wp*Nw.' + 2*up*Nu.') +...
     2*l2*((NtetaX.' + NtetaY.'*tetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
           (tetaXp + tetaYp*tetaZ)*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))) +...
     2*l2*((Nu.' - Nw.'*tetaY)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
           (up - wp*tetaY)*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))) +...
     l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) -...
     2*(Nv.'*(wp*tetaZ*tetaY + tetaZ*l2*tetaZp*cos(tetaX + alfa) + l2*tetaXp*sin(tetaX + alfa)) +...
        vp*(Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa))));
dPsiTdm_nlnduj = dm*(l2^2*(2*tetaXp*tetaYp + tetaYp^2*2*tetaZ)*NtetaZ.' +...
    2*tetaZ*NtetaZ.'*(vp^2 + up^2) +...
    2*tetaY*NtetaY.'*(wp^2 + up^2) +...
    2*l2*((tetaYp*NtetaZ.')*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
          (tetaXp + tetaYp*tetaZ)*(up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                       (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) - wp*sin(tetaX + alfa)*NtetaX.')) +...
    2*l2*((-wp*NtetaY.')*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
          (up - wp*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.') +...
    l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.' -...
    2*vp*(wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
    l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
    l2*tetaXp*cos(tetaX + alfa)*NtetaX.'));

d2PsiTdm_lndtdupj = dm*(2*Nu.'*upp + 2*Nv.'*vpp + 2*Nw.'*wpp + l2^2*2*NtetaX.'*tetaXpp);
%{
d2PsiTdm_lndtdupjRef = diff(dPsiTdm_lndupj,t);
erro = simplify(d2PsiTdm_lndtdupjRef - d2PsiTdm_lndtdupj);
ad = 1;
%ok!
%}

M1jdm = 2*dm*(Nu.'*Nu + Nv.'*Nv + Nw.'*Nw + l2^2*(NtetaX.'*NtetaX));
%{
erro = simplify(d2PsiTdm_lndtdupj - M1jdm*uppj);
ad = 1;
%ok!
%}
%{
dPsiTdmnlndupj1 = dm*...
    (l2^2*(2*tetaZ*(NtetaX.'*tetaYp + tetaXp*NtetaY.') + 2*tetaYp*NtetaY.'*tetaZ^2) +...
     tetaZ^2*(2*vp*Nv.' + 2*up*Nu.') + tetaY^2*(2*wp*Nw.' + 2*up*Nu.'));
dPsiTdmnlndupj2 = dm*...
    (2*l2*((NtetaX.' + NtetaY.'*tetaZ)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
           (tetaXp + tetaYp*tetaZ)*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))));
dPsiTdmnlndupj3 = dm*...
    (2*l2*((Nu.' - Nw.'*tetaY)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
           (up - wp*tetaY)*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))));
dPsiTdmnlndupj4 = dm*...
    (l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) -...
     2*(Nv.'*(wp*tetaZ*tetaY + tetaZ*l2*tetaZp*cos(tetaX + alfa) + l2*tetaXp*sin(tetaX + alfa)) +...
        vp*(Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa))));
%{
erro = simplify(dPsiTdm_nlndupj - (dPsiTdmnlndupj1 + dPsiTdmnlndupj2 + dPsiTdmnlndupj3 + dPsiTdmnlndupj4));
ad = 1;
%ok!
%}

d2PsiTdmnlndtdupj1 = dm*...
    (l2^2*(2*(tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.') + tetaZ*(NtetaX.'*tetaYpp + tetaXpp*NtetaY.')) +...
           2*(tetaYpp*tetaZ^2 + 2*tetaZ*tetaYp*tetaZp)*NtetaY.') +...
     (2*tetaZ*tetaZp*(2*vp*Nv.' + 2*up*Nu.') + tetaZ^2*(2*vpp*Nv.' + 2*upp*Nu.')) +...
     (2*tetaY*tetaYp*(2*wp*Nw.' + 2*up*Nu.') + tetaY^2*(2*wpp*Nw.' + 2*upp*Nu.')));
%{
d2PsiTdmnlndtdupj1Ref = diff(dPsiTdmnlndupj1,t);
erro = simplify(d2PsiTdmnlndtdupj1Ref - d2PsiTdmnlndtdupj1);
ad = 1;
%ok!
%}
d2PsiTdmnlndtdupj2 = dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((upp*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) +...
                                          up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                         (wpp*cos(tetaX + alfa) - wp*sin(tetaX + alfa)*tetaXp))) +...
           ((tetaXpp + (tetaYpp*tetaZ + tetaYp*tetaZp))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
            (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*tetaXp +...
                                     Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                           (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))))));
%{
d2PsiTdmnlndtdupj2Ref = diff(dPsiTdmnlndupj2,t);
erro = simplify(d2PsiTdmnlndtdupj2Ref - d2PsiTdmnlndtdupj2);
ad = 1;
%ok!
%}
d2PsiTdmnlndtdupj3 = dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (Nu.' - Nw.'*tetaY)*((tetaYpp*sin(tetaX + alfa) + tetaYp*cos(tetaX + alfa)*tetaXp) -...
                                 (tetaZpp*cos(tetaX + alfa) - tetaZp*sin(tetaX + alfa)*tetaXp))) +...
           ((upp - (wpp*tetaY + wp*tetaYp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
            (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp))));
%{
d2PsiTdmnlndtdupj3Ref = diff(dPsiTdmnlndupj3,t);
erro = simplify(d2PsiTdmnlndtdupj3Ref - d2PsiTdmnlndtdupj3);
ad = 1;
%ok!
%}   
d2PsiTdmnlndtdupj4 = dm*...
    (l2^2*2*(((tetaYpp*sin(tetaX + alfa) + tetaYp*cos(tetaX + alfa)*tetaXp) - (tetaZpp*cos(tetaX + alfa) - tetaZp*sin(tetaX + alfa)*tetaXp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
             (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)) -...
     2*(Nv.'*((wpp*tetaZ*tetaY + wp*tetaZp*tetaY + wp*tetaZ*tetaYp) +...
              (tetaZp^2*cos(tetaX + alfa) + tetaZ*tetaZpp*cos(tetaX + alfa) - tetaZ*tetaZp*sin(tetaX + alfa)*tetaXp)*l2 +...
              (tetaXpp*sin(tetaX + alfa) + tetaXp^2*cos(tetaX + alfa))*l2) +...
        (vpp*(Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa)) +...
         vp*(Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
             l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
             l2*NtetaX.'*cos(tetaX + alfa)*tetaXp))));
%{
d2PsiTdmnlndtdupj4Ref = diff(dPsiTdmnlndupj4,t);
erro = simplify(d2PsiTdmnlndtdupj4Ref - d2PsiTdmnlndtdupj4);
ad = 1;
%ok!
%}   
%}
d2PsiTdm_nlndtdupj = ...
    dm*...
    (l2^2*(2*(tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.') + tetaZ*(NtetaX.'*tetaYpp + tetaXpp*NtetaY.')) +...
           2*(tetaYpp*tetaZ^2 + 2*tetaZ*tetaYp*tetaZp)*NtetaY.') +...
     (2*tetaZ*tetaZp*(2*vp*Nv.' + 2*up*Nu.') + tetaZ^2*(2*vpp*Nv.' + 2*upp*Nu.')) +...
     (2*tetaY*tetaYp*(2*wp*Nw.' + 2*up*Nu.') + tetaY^2*(2*wpp*Nw.' + 2*upp*Nu.'))) +...
    dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((upp*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) +...
                                          up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                         (wpp*cos(tetaX + alfa) - wp*sin(tetaX + alfa)*tetaXp))) +...
           ((tetaXpp + (tetaYpp*tetaZ + tetaYp*tetaZp))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
            (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*tetaXp +...
                                     Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                           (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))))) +...
    dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (Nu.' - Nw.'*tetaY)*((tetaYpp*sin(tetaX + alfa) + tetaYp*cos(tetaX + alfa)*tetaXp) -...
                                 (tetaZpp*cos(tetaX + alfa) - tetaZp*sin(tetaX + alfa)*tetaXp))) +...
           ((upp - (wpp*tetaY + wp*tetaYp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
            (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)))) +...
    dm*...
    (l2^2*2*(((tetaYpp*sin(tetaX + alfa) + tetaYp*cos(tetaX + alfa)*tetaXp) - (tetaZpp*cos(tetaX + alfa) - tetaZp*sin(tetaX + alfa)*tetaXp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
             (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)) -...
     2*(Nv.'*((wpp*tetaZ*tetaY + wp*tetaZp*tetaY + wp*tetaZ*tetaYp) +...
              (tetaZp^2*cos(tetaX + alfa) + tetaZ*tetaZpp*cos(tetaX + alfa) - tetaZ*tetaZp*sin(tetaX + alfa)*tetaXp)*l2 +...
              (tetaXpp*sin(tetaX + alfa) + tetaXp^2*cos(tetaX + alfa))*l2) +...
        (vpp*(Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa)) +...
         vp*(Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
             l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
             l2*NtetaX.'*cos(tetaX + alfa)*tetaXp))));
%{
d2PsiTdm_nlndtdupjRef = diff(dPsiTdm_nlndupj,t);
erro = simplify(d2PsiTdm_nlndtdupjRef - d2PsiTdm_nlndtdupj);
ad = 1;
%ok!
%}
M2uppjdm = ...
    dm*...
    (l2^2*(2*tetaZ*(NtetaX.'*tetaYpp + tetaXpp*NtetaY.') +...
           2*tetaYpp*tetaZ^2*NtetaY.') +...
     (tetaZ^2*(2*vpp*Nv.' + 2*upp*Nu.')) +...
     (tetaY^2*(2*wpp*Nw.' + 2*upp*Nu.'))) +...
    dm*...
    (2*l2*(((NtetaX.' + NtetaY.'*tetaZ)*((upp*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
                                         (wpp*cos(tetaX + alfa)))) +...
           ((tetaXpp + (tetaYpp*tetaZ))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))))) +...
    dm*...
    (2*l2*(((Nu.' - Nw.'*tetaY)*((tetaYpp*sin(tetaX + alfa)) -...
                                 (tetaZpp*cos(tetaX + alfa)))) +...
           ((upp - (wpp*tetaY))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))))) +...
    dm*...
    (l2^2*2*(((tetaYpp*sin(tetaX + alfa)) - (tetaZpp*cos(tetaX + alfa)))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))) -...
     2*(Nv.'*((wpp*tetaZ*tetaY) +...
              (tetaZ*tetaZpp*cos(tetaX + alfa))*l2 +...
              (tetaXpp*sin(tetaX + alfa))*l2) +...
        (vpp*(Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa)))));
%{
gC1jdm = ...
    dm*...
    (l2^2*(2*(tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.')) +...
           2*(2*tetaZ*tetaYp*tetaZp)*NtetaY.') +...
     (2*tetaZ*tetaZp*(2*vp*Nv.' + 2*up*Nu.')) +...
     (2*tetaY*tetaYp*(2*wp*Nw.' + 2*up*Nu.'))) +...
    dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                         (-wp*sin(tetaX + alfa)*tetaXp))) +...
           (((tetaYp*tetaZp))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
            (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*tetaXp +...
                                     Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                           (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))))) +...
    dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (Nu.' - Nw.'*tetaY)*((tetaYp*cos(tetaX + alfa)*tetaXp) -...
                                 (-tetaZp*sin(tetaX + alfa)*tetaXp))) +...
           ((-(wp*tetaYp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
            (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)))) +...
    dm*...
    (l2^2*2*(((tetaYp*cos(tetaX + alfa)*tetaXp) - (-tetaZp*sin(tetaX + alfa)*tetaXp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
             (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)) -...
     2*(Nv.'*((wp*tetaZp*tetaY + wp*tetaZ*tetaYp) +...
              (tetaZp^2*cos(tetaX + alfa) - tetaZ*tetaZp*sin(tetaX + alfa)*tetaXp)*l2 +...
              (tetaXp^2*cos(tetaX + alfa))*l2) +...
        (vp*(Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
             l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
             l2*NtetaX.'*cos(tetaX + alfa)*tetaXp))));
erro = simplify(d2PsiTdm_nlndtdupj - (M2uppjdm + gC1jdm));
ad = 1;
%ok!
%}
%{
M2jdm = ...
    dm*...
    (l2^2*(2*tetaZ*(NtetaX.'*NtetaY + NtetaY.'*NtetaX) +...
           2*tetaZ^2*(NtetaY.'*NtetaY)) +...
     (tetaZ^2*(2*(Nv.'*Nv) + 2*(Nu.'*Nu))) +...
     (tetaY^2*(2*(Nw.'*Nw) + 2*(Nu.'*Nu)))) +...
    dm*...
    (2*l2*(((NtetaX.' + NtetaY.'*tetaZ)*(((tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))*Nu) +...
                                         (Nw*cos(tetaX + alfa)))) +...
           ((Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)))*(NtetaX + (NtetaY*tetaZ))))) +...
    dm*...
    (2*l2*(((Nu.' - Nw.'*tetaY)*((NtetaY*sin(tetaX + alfa)) -...
                                 (NtetaZ*cos(tetaX + alfa)))) +...
           ((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*(Nu - (Nw*tetaY))))) +...
    dm*...
    (l2^2*2*((NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))*((NtetaY*sin(tetaX + alfa)) - (NtetaZ*cos(tetaX + alfa)))) -...
     2*(Nv.'*((Nw*tetaZ*tetaY) +...
              (tetaZ*NtetaZ*cos(tetaX + alfa))*l2 +...
              (NtetaX*sin(tetaX + alfa))*l2) +...
        ((Nw.'*tetaZ*tetaY + tetaZ*l2*NtetaZ.'*cos(tetaX + alfa) + l2*NtetaX.'*sin(tetaX + alfa))*Nv)));
%{
erro = simplify(M2uppjdm - M2jdm*uppj);
ad = 1;
%ok!
%}    
%}

dMuppjdm =...
    dm*...
    (2*l2*((NtetaX.')*(wpp*cos(tetaX + alfa)) +...
           (tetaXpp)*(Nw.'*cos(tetaX + alfa)))) +...
    dm*...
    (2*l2*(((Nu.')*(tetaYpp*sin(tetaX + alfa) -...
                    tetaZpp*cos(tetaX + alfa))) +...
           ((upp)*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))))) +...
    dm*...
    (l2^2*2*(((tetaYpp*sin(tetaX + alfa)) - (tetaZpp*cos(tetaX + alfa)))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa))) -...
     l2*2*(Nv.'*tetaXpp*sin(tetaX + alfa) +...
           vpp*l2*NtetaX.'*sin(tetaX + alfa)));
        
gCjdm = dm*...
    (l2^2*(2*(tetaZp*(NtetaX.'*tetaYp + tetaXp*NtetaY.')) +...
           2*(2*tetaZ*tetaYp*tetaZp)*NtetaY.') +...
     (2*tetaZ*tetaZp*(2*vp*Nv.' + 2*up*Nu.')) +...
     (2*tetaY*tetaYp*(2*wp*Nw.' + 2*up*Nu.'))) +...
    dm*...
    (2*l2*(((NtetaY.'*tetaZp)*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
            (NtetaX.' + NtetaY.'*tetaZ)*((up*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                              (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp))) +...
                                         (-wp*sin(tetaX + alfa)*tetaXp))) +...
           (((tetaYp*tetaZp))*(Nw.'*cos(tetaX + alfa) + Nu.'*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa))) +...
            (tetaXp + tetaYp*tetaZ)*(-Nw.'*sin(tetaX + alfa)*tetaXp +...
                                     Nu.'*((tetaZp*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*tetaXp) +...
                                           (tetaYp*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*tetaXp)))))) +...
    dm*...
    (2*l2*(((-Nw.'*tetaYp)*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
            (Nu.' - Nw.'*tetaY)*((tetaYp*cos(tetaX + alfa)*tetaXp) -...
                                 (-tetaZp*sin(tetaX + alfa)*tetaXp))) +...
           ((-(wp*tetaYp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
            (up - wp*tetaY)*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)))) +...
    dm*...
    (l2^2*2*(((tetaYp*cos(tetaX + alfa)*tetaXp) - (-tetaZp*sin(tetaX + alfa)*tetaXp))*(NtetaY.'*sin(tetaX + alfa) - NtetaZ.'*cos(tetaX + alfa)) +...
             (tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(NtetaY.'*cos(tetaX + alfa)*tetaXp + NtetaZ.'*sin(tetaX + alfa)*tetaXp)) -...
     2*(Nv.'*((wp*tetaZp*tetaY + wp*tetaZ*tetaYp) +...
              (tetaZp^2*cos(tetaX + alfa) - tetaZ*tetaZp*sin(tetaX + alfa)*tetaXp)*l2 +...
              (tetaXp^2*cos(tetaX + alfa))*l2) +...
        (vp*(Nw.'*(tetaZp*tetaY + tetaZ*tetaYp) +...
             l2*NtetaZ.'*(tetaZp*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*tetaXp) +...
             l2*NtetaX.'*cos(tetaX + alfa)*tetaXp)))) -...
    dm*(l2^2*(2*tetaXp*tetaYp + tetaYp^2*2*tetaZ)*NtetaZ.' +...
    2*tetaZ*NtetaZ.'*(vp^2 + up^2) +...
    2*tetaY*NtetaY.'*(wp^2 + up^2) +...
    2*l2*((tetaYp*NtetaZ.')*(up*(tetaZ*sin(tetaX + alfa) + tetaY*cos(tetaX + alfa)) + wp*cos(tetaX + alfa)) +...
          (tetaXp + tetaYp*tetaZ)*(up*((NtetaZ.'*sin(tetaX + alfa) + tetaZ*cos(tetaX + alfa)*NtetaX.') +...
                                       (NtetaY.'*cos(tetaX + alfa) - tetaY*sin(tetaX + alfa)*NtetaX.')) - wp*sin(tetaX + alfa)*NtetaX.')) +...
    2*l2*((-wp*NtetaY.')*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa)) +...
          (up - wp*tetaY)*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.') +...
    l2^2*2*(tetaYp*sin(tetaX + alfa) - tetaZp*cos(tetaX + alfa))*(tetaYp*cos(tetaX + alfa) + tetaZp*sin(tetaX + alfa))*NtetaX.' -...
    2*vp*(wp*(NtetaZ.'*tetaY + tetaZ*NtetaY.') +...
    l2*tetaZp*(NtetaZ.'*cos(tetaX + alfa) - tetaZ*sin(tetaX + alfa)*NtetaX.') +...
    l2*tetaXp*cos(tetaX + alfa)*NtetaX.'));
%{
gC2jdm = -dPsiTdm_nlnduj;
gCjdmRef = gC1jdm + gC2jdm;
erro = simplify(gCjdmRef - gCjdm);
ad = 1;
%ok!
%}

%%
%Movimento de M1:
%{
IIv1 = [upNM1; vpNM1; wpNM1];
B2IwC1 = [ tetaXpNM1 + tetaYpNM1*tetaZNM1; tetaYpNM1; tetaZpNM1];

Ibb1 = diag([Ip1, I1, I1]);
PsiT1_x = M1*(IIv1.'*IIv1) + B2IwC1.'*Ibb1*B2IwC1;

PsiT1_ln = M1*(upNM1^2 + vpNM1^2 + wpNM1^2) + Ip1*tetaXpNM1^2 + I1*tetaYpNM1^2 + I1*tetaZpNM1^2;
PsiT1_nln = Ip1*(2*tetaXpNM1*tetaZNM1*tetaYpNM1 + tetaZNM1^2*tetaYpNM1^2);
%}
%Elemento j=N: xi=1
M1j1 = 2*...
    (M1*((Nu.'*Nu) + (Nv.'*Nv) + (Nw.'*Nw)) +...
     Ip1*(NtetaX.'*NtetaX) +...
     I1*(NtetaY.'*NtetaY) +...
     I1*(NtetaZ.'*NtetaZ));

M2uppj1 = 2*Ip1*(tetaZ*(NtetaX.'*NtetaY + NtetaY.'*NtetaX) + tetaZ^2*(NtetaY.'*NtetaY))*uppj;

gCj1 = 2*Ip1*...
    (NtetaX.'*tetaZp*tetaYp +...
     NtetaY.'*tetaZp*(tetaXp + 2*tetaZ*tetaYp) -...
     NtetaZ.'*tetaYp*(tetaXp + tetaZ*tetaYp));

%%
%Movimento de M2:
%{
IIv2 = [upN1M1; vpN1M1; wpN1M1];
B2IwC2 = [ tetaXpN1M1 + tetaYpN1M1*tetaZN1M1; tetaYpN1M1; tetaZpN1M1];

Ibb2 = diag([Ip2, I2, I2]);
PsiT2_x = M2b*(IIv2.'*IIv2) + B2IwC2.'*Ibb2*B2IwC2;

PsiT2_ln = M2b*(upN1M1^2 + vpN1M1^2 + wpN1M1^2) + Ip2*tetaXpN1M1^2 + I2*tetaYpN1M1^2 + I2*tetaZpN1M1^2;
PsiT2_nln = Ip2*(2*tetaXpN1M1*tetaZN1M1*tetaYpN1M1 + tetaZN1M1^2*tetaYpN1M1^2);
%}
%Elemento N1: xi=1
%Elemento N1+1: xi=0
M1j2 = 2*...
    (M2b*((Nu.'*Nu) + (Nv.'*Nv) + (Nw.'*Nw)) +...
     Ip2b*(NtetaX.'*NtetaX) +...
     I2b*(NtetaY.'*NtetaY) +...
     I2b*(NtetaZ.'*NtetaZ));

M2uppj2 = 2*Ip2b*(tetaZ*(NtetaX.'*NtetaY + NtetaY.'*NtetaX) + tetaZ^2*(NtetaY.'*NtetaY))*uppj;

gCj2 = 2*Ip2b*...
    (NtetaX.'*tetaZp*tetaYp +...
     NtetaY.'*tetaZp*(tetaXp + 2*tetaZ*tetaYp) -...
     NtetaZ.'*tetaYp*(tetaXp + tetaZ*tetaYp));

%%
%Movimento de M3:
%{
IIv3 = [up3; vp3; wp3];
B2IwC3 = [ tetaYp1*tetaZ1; tetaYp1; tetaZp1]; 
%Obs.: 
%(1) M3 se refere à massa da plataforma móvel, que não será induzida a ter 
%    velocidade tetaXp

Ibb3 = diag([Ip3, I3, I3]);
PsiT3_x = M3*(IIv3.'*IIv3) + B2IwC3.'*Ibb3*B2IwC3;

PsiT3_ln = M3*(up1^2 + vp1^2 + wp1^2) + I3*tetaYp1^2 + I3*tetaZp1^2;
PsiT3_nln = Ip3*(tetaZ1^2*tetaYp1^2);
%}
syms Ip3pl I3pl
%Elemento 1: xi=0
M1j3 = 2*...
    (M3pl*((Nu.'*Nu) + (Nv.'*Nv) + (Nw.'*Nw)) +...
     I3pl*(NtetaY.'*NtetaY) +...
     I3pl*(NtetaZ.'*NtetaZ));

M2uppj3 = 2*Ip3pl*tetaZ^2*(NtetaY.'*tetaYpp);

M2j3 = 2*Ip3pl*(tetaZ^2*(NtetaY.'*NtetaY));

gCj3 = 2*Ip3pl*...
    (NtetaY.'*tetaZp*(2*tetaZ*tetaYp) -...
     NtetaZ.'*tetaYp*(tetaZ*tetaYp));

%% 
%Movimento da inércia do motor:
%{
B2IwC3m = [ tetaXp1; 0; 0];

Ibb3m = diag([Ip3m, I3m, I3m]);
PsiT3m_x = B2IwC3m.'*Ibb2*B2IwC3m;

PsiT3m_ln = Ip3m*tetaXp1^2;
%}
%Elemento 1: xi=0
syms Ip3mt
M1j3m = 2*Ip3mt*(NtetaX.'*NtetaX);
















